### ISSUE TITLE
4.3. Xử lý Notification Service

### ISSUE THREAD

**Issue by chabuuuu** [ASE-UIT/02.-Online-course-System#208]
Vào notification.service.ts => mình đã định nghĩa sẵn các hàm. Bạn có nhiệm vụ hoàn thiện các hàm này (chi tiết từng hàm sẽ làm gì mình đã comment trên đầu từng hàm)

**Comment by PhanTranTienHung22520523** [comment]
đã xong, Thịnh check giúp tui với nha
